### ISSUE TITLE
[Docs] Connections says database will be added later, has database info already

### ISSUE THREAD

**Issue by javorszky** [suborbital/atmo#115]
https://atmo.suborbital.dev/usage/connections

> Currently, Atmo can connect to NATS and Redis, and upcoming releases will include additional types such as databases and more.

vs further down

> SQL databases and caches can be connected to Atmo to be made available to your Runnables using the Runnable API:
> ...
> SQL database connections of type mysql and postgresql are available, and they are discussed in detail in the next section.

I think we can remove the "databases are coming" part from the top.

**Comment by cohix** [comment]
Good call @javorszky, seeing as we're transitioning away from specific-repo docs and moving everything into the suborbital/docs repo, could you move this issue (and possibly fix it ;P) over there?
