### ISSUE TITLE
Is SCC stuff part of Atmo ?

### ISSUE THREAD

**Issue by gedw99** [suborbital/atmo#192]
https://docs.suborbital.dev/compute/concepts/data-plane-vs-control-plane/

**Comment by gedw99** [comment]
I ask because I want to use cuelang with atmo . Cuelang is pretty cool because all types / Schemata for data between the functions can be checked as well as versioned.

**Comment by gedw99** [comment]
Cue can compile to wasm btw

**Comment by ospencer** [comment]
Hey @gedw99, you're looking at the documentation for Suborbital Compute, our product that lets you extend your apps with user-defined functions. You can find the documentation for Atmo here: https://docs.suborbital.dev/atmo/

I'm not super familiar with Cue, but depending on where the integration parts are you may be able to put something together. If you've got specific questions, I'm happy to answer them!

**Comment by gedw99** [comment]
i changed to using https://github.com/yomorun for now to see how that goes.
