### ISSUE TITLE
Can Runnables be organized in ad hoc subdirectories?

### ISSUE THREAD

**Issue by kee-oth** [suborbital/atmo#210]
Hi!

I'm wondering if Runnables have to stay in the project root or if there's a way to organize them into ad hoc subdirectories.

Right now, we need to keep Runnables in the root like
```
myRunnableDirectory/
Directive.yaml
```

It'd be great to be able to put them in subdirectories for organization purposes like
```
Resources/Accounts/myRunnableDirectory
Resources/Accounts/myOtherRunnableDirectory
Resources/Files/getAll
Resources/Files/delete
Directive.yaml
```

Thanks!

**Comment by cohix** [comment]
@kee-oth yes, currently they need to be in the project root, however we are changing that. We are working on updates to the CLI which will allow for arbitrary folders.
