### ISSUE TITLE
Question - Code organization 

### ISSUE THREAD

**Issue by felippemr** [suborbital/atmo#29]
👋   First and foremost, I love the solution you are all building.

Some questions I had while playing with atmo were:

1. Let's say I need to create a simple CRUD API and the only difference between the different routes is the database table they operate over, what would be a good approach to solve this problem?
2. How versioning is handled by atmo?
    - If have been running an app in atmo for a month and deployed one new app version each week, at the end of the month would I be able to know which version was running in a specific day?
3.  Can atmo handle gRPC/protobuf?
4. How would I handle AuthN and AuthZ?
5. Can I run atmo in kubernetes?

 Thanks!

**Comment by cohix** [comment]
Thank you for the kind words!

For your first question, I'm not sure I have a good answer. I added the concept of 'initial state' for scheduled jobs, and I may end up doing so for request handlers as well. That would let you set 'table: foobar' on each one and then use req::state to access the value in your Runnables. Would that solve the problem for you?

As for versions, the Directive has an appVersion field which is meant to indicate the version of your application. Your comment made me realize that the Atmo version is included in structured logs but not the appVersion. Would including that help?

Atmo cannot currently handle gRPC. A gRPC Transport for [Grav](https://github.com/suborbital/grav) is being worked on which will eventually allow Atmo instances to communicate with each other via gRPC, but that doesn't solve what I assume you would like to do which is handle gRPC requests using Atmo?

AuthN and AuthZ would be handled by your application code. I plan on adding middleware so you can add Runnables that run on route groups, in a similar manner to how [Vektor](https://github.com/suborbital/vektor) handles them.

You absolutely can use Kubernetes! Check out the new experimental [K8s repo](https://github.com/suborbital/atmo-k8s-helm) and please give your feedback! Please note it's currently optimized for K3s so it may need some tweaking. 

Let me know about the above and we can get some issues filed to track them.

**Comment by felippemr** [comment]
> For your first question, I'm not sure I have a good answer. I added the concept of 'initial state' for scheduled jobs, and I may end up doing so for request handlers as well. That would let you set 'table: foobar' on each one and then use req::state to access the value in your Runnables. Would that solve the problem for you?

I think it would, I can't think of a red flag from the top of my mind.

> As for versions, the Directive has an appVersion field which is meant to indicate the version of your application. Your comment made me realize that the Atmo version is included in structured logs but not the appVersion. Would including that help?

Yes, and I am open to contributing as well if you direct me to the right place.


> Atmo cannot currently handle gRPC. A gRPC Transport for Grav is being worked on which will eventually allow Atmo instances to communicate with each other via gRPC, but that doesn't solve what I assume you would like to do which is handle gRPC requests using Atmo?

Not currently, my most immediate need is only HTTP REST API.

> AuthN and AuthZ would be handled by your application code. I plan on adding middleware so you can add Runnables that run on route groups, in a similar manner to how Vektor handles them.

Got it, thanks!

> You absolutely can use Kubernetes! Check out the new experimental K8s repo and please give your feedback! Please note it's currently optimized for K3s so it may need some tweaking.

🎉 

Thanks!

**Comment by felippemr** [comment]
I basically want to implement https://standards.openbanking.org.uk/api-specifications/ using atmos and amazon QLDB, and provide it as a service.

**Comment by cohix** [comment]
> I basically want to implement https://standards.openbanking.org.uk/api-specifications/ using atmos and amazon QLDB, and provide it as a service.

That is really awesome! Let's make it happen. If you're interested, find a time to meet? https://meet.suborbital.dev/30m 

If not, you can email me connor at suborbital.dev

**Comment by felippemr** [comment]
Scheduled some time for tomorrow 6 am PST.
