### ISSUE TITLE
Newsletter signup ack broken link

### ISSUE THREAD

**Issue by jimt** [suborbital/atmo#53]
The **Thank you for subscribing** email response to confirming a newsletter subscription includes:

> You will receive updates straight to your inbox, but you can also check out the backlog for past and future issues.

The tracking link on **backlog** redirects to https://subscribe.suborbital.dev/ which does not resolve.

(Sorry, I couldn't find your website repository.)

**Comment by cohix** [comment]
@jimt thank you for pointing this out! I will change the setting via the newsletter provider (Revue)
