### ISSUE TITLE
Wasmer linker issue on Linux x86_64

### ISSUE THREAD

**Issue by jagger27** [suborbital/atmo#65]
When building Atmo on Linux, the Wasmer library isn't found:
```
$ make atmo
go build -o .bin/atmo ./main.go
# github.com/wasmerio/wasmer-go/wasmer
/usr/bin/ld: cannot find -lwasmer
collect2: error: ld returned 1 exit status
make: *** [Makefile:3: build] Error 2
```

Workaround:

Wasmer ships pre-built libraries in their repo.

`go get github.com/wasmerio/wasmer-go/wasmer` followed by `go mod vendor` fixes the dependency issue.

**Comment by ospencer** [comment]
Done!
