### ISSUE TITLE
Can I author wasm using tinygo ?

### ISSUE THREAD

**Issue by gedw99** [suborbital/atmo#71]
Just wanted to know if tinygo or the standard golang compiler is supported ?

**Comment by cohix** [comment]
@gedw99 we are working on TinyGo support, I hope to have it within a few weeks!

**Comment by jagger27** [comment]
Doesn’t standard Go have a Wasm target already?

**Comment by gedw99** [comment]
thanks for the responses - cant wait to try this out...

@jagger27 thanks for the link. From reading it, it looks like many others and wanting this and its going to happen.

**Comment by cohix** [comment]
Certainly, we will use TinyGo for now, and as the standard Go toolchain matures we'll look at that as well!

@jagger27 has made some progress on this, so hopefully we'll have more to share soon!

**Comment by ospencer** [comment]
@gedw99 we added support for TinyGo in the most recent release! Check it out and let us know what you think 🙂
